---

is_debug: true
is_development: true
listen:
  type: port
  bind_p: 0.0.0.0
  port: 10006
app:
  log_level: trace
Telegram:
  Token: '5347241093:AAHhBE-pyCpUDQitwmbZG0BNnLsnbJg5u2E'

messages:
  start: ''
keyboards:
  help: ''
  recyclingBin: ''
  category: ''
  
